let Homes = [
    {
        "id" : 1,
        // "image" : "./components/img/home_1.png",
        // "owner" : "././components/img/owner_1.png",
        "image":"https://picsum.photos/380/220",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 2,
        // "image" : "./components/img/home_2.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/381/220",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,900/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 3,
        // "image" : "./components/img/home_3.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/380/221",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 4,
        // "image" : "./components/img/home_2.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/379/220",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 5,
        // "image" : "./components/img/home_3.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/380/219",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 6,
        // "image" : "./components/img/home_1.png",
        // "owner" : "././components/img/owner_1.png",
        "image":"https://picsum.photos/381/221",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 7,
        // "image" : "./components/img/home_3.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/379/219",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 8,
        // "image" : "./components/img/home_1.png",
        // "owner" : "././components/img/owner_1.png",
        "image":"https://picsum.photos/383/219",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 9,
        // "image" : "./components/img/home_2.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/379/223",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 10,
        // "image" : "./components/img/home_1.png",
        // "owner" : "././components/img/owner_1.png",
        "image":"https://picsum.photos/388/222",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 11,
        // "image" : "./components/img/home_2.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/381/225",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 12,
        // "image" : "./components/img/home_3.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/381/224",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 13,
        // "image" : "./components/img/home_3.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/385/222",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
     {
        "id" : 14,
        // "image" : "./components/img/home_1.png",
        // "owner" : "././components/img/owner_1.png",
        "image":"https://picsum.photos/386/222",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 15,
        // "image" : "./components/img/home_2.png",
        // "owner" : "././components/img/owner_2.png",
        "image":"https://picsum.photos/381/226",
        "owner":"https://picsum.photos/38/38",
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },  
];

export default Homes;