import home_1 from './components/img/home_1.png'
import home_2 from './components/img/home_2.png'
import home_3 from './components/img/home_3.png'
import owner_1 from './components/img/owner_1.png'
import owner_2 from './components/img/owner_2.png'
let Homes = [
    {
        "id" : 1,
        "image" : home_1,
        "owner" : owner_1,
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 2,
        "image" : home_2,
        "owner" : owner_2,
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,900/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 3,
        "image" : home_3,
        "owner" : owner_2,
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 4,
        "image" : home_2,
        "owner" : owner_2,
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 5,
        "image" : home_3,
        "owner" : owner_2,
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 6,
        "image" : home_1,
        "owner" : owner_1,
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 7,
        "image" : home_3,
        "owner" : owner_2,
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 8,
        "image" : home_1,
        "owner" : owner_1,
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 9,
        "image" : home_2,
        "owner" : owner_2,
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 10,
        "image" : home_1,
        "owner" : owner_1,
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 11,
        "image" : home_2,
        "owner" : owner_2,
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },
    {
        "id" : 12,
        "image" : home_3,
        "owner" : owner_2,
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
    {
        "id" : 13,
        "image" : home_3,
        "owner" : owner_2,
        "houseName" : "New Huge Apartment ",
        "location":"Boulevard St, Canada, USA",
        "beds":"12 Beds",
        "baths":"8 Baths",
        "garage":"2 Garage",
        "measurement":"1800 Sq Ft",
        "OPrice":"$4,800/mo",
        "price":"$12,100/mo",
    },
     {
        "id" : 14,
        "image" : home_1,
        "owner" : owner_1,
        "houseName" : "New Apartment Nice Wiew",
        "location":"Quincy St, Brooklyn, NY, USA",
        "beds":"8 Beds",
        "baths":"5 Baths",
        "garage":"1 Garage",
        "measurement":"1200 Sq Ft",
        "OPrice":"$2,800/mo",
        "price":"$7,500/mo",
    },
    {
        "id" : 15,
        "image" : home_2,
        "owner" : owner_2,
        "houseName" : "Nice Apartment",
        "location":"Quebec St,  Canada",
        "beds":"10 Beds",
        "baths":"6 Baths",
        "garage":"2 Garage",
        "measurement":"1400 Sq Ft",
        "OPrice":"$3,000/mo",
        "price":"$8,500/mo",
    },  
];

export default Homes;